### ISSUE TITLE
please remove BARD IS READY notification, and give us a chatscreen like copilot, its very annoying

### ISSUE THREAD

**Issue by fisforfaheem** [TPJelf/askbard#1]

**Comment by TPJelf** [comment]
The bard is ready notification should only appear once per extension load, are you seeing it more often?

**Comment by fisforfaheem** [comment]
yes every time i open vscode ... also we need a chatbox like copilot

**Comment by TPJelf** [comment]
Ok, that's the expected behavior. I'll add settings to mute the notifications.
Coding the chat depends on Google releasing a Gemini API.

**Comment by TPJelf** [comment]
Google granted free Gemini access so I'm pushing a new update this weekend. I'll get the mute notifications settings done for sure, the chat will have to wait.

**Comment by TPJelf** [comment]
Added notification option. UI rework is in the works.
